entrada = input('Digite algo: ')
print(f'Tipo primitivo desse valor: {type(entrada)}')
print(f'Só tem espaço? {entrada.isspace()}')
print(f'É um número? {entrada.isnumeric()}')
print(f'É alfabético? {entrada.isalpha()}')
print(f'É alfanumérico? {entrada.isalnum()}')
print(f'Está minúsculo? {entrada.islower()}')
print(f'Está em maiúsculo? {entrada.isupper()}')
print(f'Está capitalizada? {entrada.istitle()}')